removed social share icons from glossary subpages
celestiaorg/celestia.org_older pull request #400
Opened 2024-09-17 12:16 UTC by udvariisti

Removed social share icons from glossary subpages.

2024-09-20 09:34 UTC, norbert-berenyi requested changes
Please delete `socialShare.js` as well, as far as I can see it is not used anywhere anymore.

2024-10-14 13:19 UTC, gabros20 approved these changes

2024-10-14 13:19 UTC, norbert-berenyi approved these changes

2024-10-14 13:21 UTC, gabros20 commented
@alex-beckett Please review and merge.

2024-10-14 14:23 UTC, merged