Learn modular update
celestiaorg/celestia.org_older pull request #56
Opened 2022-05-27 11:50 UTC by alexbeckettt

- Add links to corresponding glossary pages for certain words in learn modular articles
- Add twitter metadata to learn modular pages so that when linked on twitter they display image cards

![egsdfa](https://user-images.githubusercontent.com/75361908/170693773-f02f2156-2ca3-4f82-880b-122286b144d9.JPG)

2022-05-30 14:27 UTC, YazzyYaz commented
From a high-level, looks good. Is there a Gatsby link I can use to view the changes?

2022-05-30 14:28 UTC, alexbeckettt commented
[Here](https://celestiaorglearnmodularupdate.gatsbyjs.io/)

2022-05-30 15:28 UTC, YazzyYaz requested changes

2022-05-30 15:28 UTC, YazzyYaz commented on src/pages/markdown-pages/learn/basics-of-modular-blockchains.md
> +<meta name="twitter:image" content="https://github.com/celestiaorg/celestia.org/blob/main/src/pages/markdown-pages/learn/images/learn-modular-twitter-card.png">
meta labels must be in <head></head>

2022-05-30 15:28 UTC, YazzyYaz commented on src/pages/markdown-pages/learn/creating-new-blockchains.md
> +<meta name="twitter:image" content="https://github.com/celestiaorg/celestia.org/blob/main/src/pages/markdown-pages/learn/images/learn-modular-twitter-card.png">
Ditto

2022-05-30 15:28 UTC, YazzyYaz commented on src/pages/markdown-pages/learn/modular-architectures.md
> +<meta name="twitter:image" content="https://github.com/celestiaorg/celestia.org/blob/main/src/pages/markdown-pages/learn/images/learn-modular-twitter-card.png">
Also here

2022-05-30 15:28 UTC, YazzyYaz commented on src/pages/markdown-pages/learn/modular-scalability.md
> +<meta name="twitter:description" content="Monolithic blockchains have pursued varying scalability techniques over time, many of which have proven unsuccessful. Modular blockchains present a way for a
Also here

2022-05-31 04:27 UTC, alexbeckettt commented
All meta tags have been moved into the <head>

2022-05-31 07:32 UTC, YazzyYaz approved these changes

2022-05-31 07:34 UTC, merged